replicaCount: ${replica_count}
name: ${deployment_name}
image:
  repository: ${image_repository}
  tag: ${image_tag}
  pullPolicy: ${image_pull_policy}
postgresql:
  host: ${postgresql_host}
  port: ${postgresql_port}
  database: ${postgresql_database}
  username: ${postgresql_username}
  passwordSecretName: ${postgresql_password_secret_name}
  DB_URL: ${postgresql_db_url}
kafka:
  broker1: ${kafka_broker1}
  broker2: ${kafka_broker2}
  broker3: ${kafka_broker3}
  topic: ${kafka_topic}
  username: ${kafka_username}
  passwordSecretName: ${kafka_password_secret_name}
initContainers:
  flywayMigration:
    name: ${flyway_migration_name}
    image: ${flyway_migration_image}
imagePullSecrets:
  - name: ${image_pull_secret_name}
volumeClaim:
  name: ${volume_claim_name}
namespace: ${namespace}
secrets:
  postgresql:
    password: ${postgresql_password}
  kafka:
    password: ${kafka_password}
  myregistrykey:
    dockerconfigjson: ${dockerconfigjson}
probes:
  liveness:
    path: ${liveness_probe_path}
    port: ${liveness_probe_port}
    initialDelaySeconds: ${liveness_probe_initial_delay_seconds}
    periodSeconds: ${liveness_probe_period_seconds}
  readiness:
    path: ${readiness_probe_path}
    port: ${readiness_probe_port}
    initialDelaySeconds: ${readiness_probe_initial_delay_seconds}
    periodSeconds: ${readiness_probe_period_seconds}
hpa:
  enabled: ${hpa_enabled}
  minReplicas: ${hpa_min_replicas}
  maxReplicas: ${hpa_max_replicas}
  targetCPUUtilizationPercentage: ${hpa_target_cpu_utilization_percentage}
  targetMemoryUtilizationPercentage: ${hpa_target_memory_utilization_percentage}
resources:
  requests:
    memory: ${resources_memory_requests}
    cpu: ${resources_cpu_requests}
  limits:
    memory: ${resources_memory_limits}
    cpu: ${resources_cpu_limits}
configMapName: ${config_map_name}
networkPolicy:
  postgresLabels:
    app: ${network_policy_postgres_labels_app}
  port: ${network_policy_port}
  metricsPort: ${network_policy_metrics_port}
podDisruptionBudget:
  enabled: ${pdb_enabled}
  minAvailable: ${pdb_min_available}
secret:
  name: ${secret_name}
  namespace: ${secret_namespace}
  serviceAccountName: ${secret_service_account_name}

serviceAccountName: {$serviceaccount}