---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgresql
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: postgresql
      app.kubernetes.io/name: postgresql
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ .Values.networkPolicy.postgresLabels.app }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.port }}
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: {{ .Values.networkPolicy.postgresLabels.app }}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.port }}
  policyTypes:
    - Ingress
    - Egress