# templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-password
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  password: {{ .Values.secrets.postgresql.password | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: kafka-password
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  password: {{ .Values.secrets.kafka.password | b64enc }}
