apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.secret.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.secret.serviceAccountName }}
type: kubernetes.io/service-account-token
